/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorklogRouteImport } from './routes/_app/worklog'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppResourcesRouteImport } from './routes/_app/resources'
import { Route as AppQualityRouteImport } from './routes/_app/quality'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppNewcomersRouteImport } from './routes/_app/newcomers'
import { Route as AppMyScoresRouteImport } from './routes/_app/my-scores'
import { Route as AppMyProjectsRouteImport } from './routes/_app/my-projects'
import { Route as AppMyProgressRouteImport } from './routes/_app/my-progress'
import { Route as AppMyPlaygroundRouteImport } from './routes/_app/my-playground'
import { Route as AppMyLearningRouteImport } from './routes/_app/my-learning'
import { Route as AppLearningRouteImport } from './routes/_app/learning'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContributorsRouteImport } from './routes/_app/contributors'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSourcesRouteImport } from './routes/_app/admin/sources'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminGrantsRouteImport } from './routes/_app/admin/grants'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminAnnouncementsRouteImport } from './routes/_app/admin/announcements'

const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorklogRoute = AppWorklogRouteImport.update({
  id: '/worklog',
  path: '/worklog',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNewcomersRoute = AppNewcomersRouteImport.update({
  id: '/newcomers',
  path: '/newcomers',
  getParentRoute: () => AppRoute,
} as any)
const AppMyScoresRoute = AppMyScoresRouteImport.update({
  id: '/my-scores',
  path: '/my-scores',
  getParentRoute: () => AppRoute,
} as any)
const AppMyProjectsRoute = AppMyProjectsRouteImport.update({
  id: '/my-projects',
  path: '/my-projects',
  getParentRoute: () => AppRoute,
} as any)
const AppMyProgressRoute = AppMyProgressRouteImport.update({
  id: '/my-progress',
  path: '/my-progress',
  getParentRoute: () => AppRoute,
} as any)
const AppMyPlaygroundRoute = AppMyPlaygroundRouteImport.update({
  id: '/my-playground',
  path: '/my-playground',
  getParentRoute: () => AppRoute,
} as any)
const AppMyLearningRoute = AppMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AppRoute,
} as any)
const AppLearningRoute = AppLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContributorsRoute = AppContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSourcesRoute = AppAdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGrantsRoute = AppAdminGrantsRouteImport.update({
  id: '/admin/grants',
  path: '/admin/grants',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnnouncementsRoute = AppAdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pending': typeof PendingRoute
  '/suspended': typeof SuspendedRoute
  '/contributors': typeof AppContributorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/learning': typeof AppLearningRoute
  '/my-learning': typeof AppMyLearningRoute
  '/my-playground': typeof AppMyPlaygroundRoute
  '/my-progress': typeof AppMyProgressRoute
  '/my-projects': typeof AppMyProjectsRoute
  '/my-scores': typeof AppMyScoresRoute
  '/newcomers': typeof AppNewcomersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/quality': typeof AppQualityRoute
  '/resources': typeof AppResourcesRoute
  '/team': typeof AppTeamRoute
  '/worklog': typeof AppWorklogRoute
  '/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/grants': typeof AppAdminGrantsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/sources': typeof AppAdminSourcesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pending': typeof PendingRoute
  '/suspended': typeof SuspendedRoute
  '/contributors': typeof AppContributorsRoute
  '/dashboard': typeof AppDashboardRoute
  '/learning': typeof AppLearningRoute
  '/my-learning': typeof AppMyLearningRoute
  '/my-playground': typeof AppMyPlaygroundRoute
  '/my-progress': typeof AppMyProgressRoute
  '/my-projects': typeof AppMyProjectsRoute
  '/my-scores': typeof AppMyScoresRoute
  '/newcomers': typeof AppNewcomersRoute
  '/onboarding': typeof AppOnboardingRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/quality': typeof AppQualityRoute
  '/resources': typeof AppResourcesRoute
  '/team': typeof AppTeamRoute
  '/worklog': typeof AppWorklogRoute
  '/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/grants': typeof AppAdminGrantsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/sources': typeof AppAdminSourcesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pending': typeof PendingRoute
  '/suspended': typeof SuspendedRoute
  '/_app/contributors': typeof AppContributorsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/learning': typeof AppLearningRoute
  '/_app/my-learning': typeof AppMyLearningRoute
  '/_app/my-playground': typeof AppMyPlaygroundRoute
  '/_app/my-progress': typeof AppMyProgressRoute
  '/_app/my-projects': typeof AppMyProjectsRoute
  '/_app/my-scores': typeof AppMyScoresRoute
  '/_app/newcomers': typeof AppNewcomersRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/_app/quality': typeof AppQualityRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/worklog': typeof AppWorklogRoute
  '/_app/admin/announcements': typeof AppAdminAnnouncementsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/grants': typeof AppAdminGrantsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/sources': typeof AppAdminSourcesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/maintenance'
    | '/pending'
    | '/suspended'
    | '/contributors'
    | '/dashboard'
    | '/learning'
    | '/my-learning'
    | '/my-playground'
    | '/my-progress'
    | '/my-projects'
    | '/my-scores'
    | '/newcomers'
    | '/onboarding'
    | '/projects'
    | '/quality'
    | '/resources'
    | '/team'
    | '/worklog'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/grants'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/users'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/maintenance'
    | '/pending'
    | '/suspended'
    | '/contributors'
    | '/dashboard'
    | '/learning'
    | '/my-learning'
    | '/my-playground'
    | '/my-progress'
    | '/my-projects'
    | '/my-scores'
    | '/newcomers'
    | '/onboarding'
    | '/projects'
    | '/quality'
    | '/resources'
    | '/team'
    | '/worklog'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/grants'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/users'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/maintenance'
    | '/pending'
    | '/suspended'
    | '/_app/contributors'
    | '/_app/dashboard'
    | '/_app/learning'
    | '/_app/my-learning'
    | '/_app/my-playground'
    | '/_app/my-progress'
    | '/_app/my-projects'
    | '/_app/my-scores'
    | '/_app/newcomers'
    | '/_app/onboarding'
    | '/_app/projects'
    | '/_app/quality'
    | '/_app/resources'
    | '/_app/team'
    | '/_app/worklog'
    | '/_app/admin/announcements'
    | '/_app/admin/audit'
    | '/_app/admin/grants'
    | '/_app/admin/settings'
    | '/_app/admin/sources'
    | '/_app/admin/users'
    | '/_app/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PendingRoute: typeof PendingRoute
  SuspendedRoute: typeof SuspendedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/worklog': {
      id: '/_app/worklog'
      path: '/worklog'
      fullPath: '/worklog'
      preLoaderRoute: typeof AppWorklogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality': {
      id: '/_app/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newcomers': {
      id: '/_app/newcomers'
      path: '/newcomers'
      fullPath: '/newcomers'
      preLoaderRoute: typeof AppNewcomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-scores': {
      id: '/_app/my-scores'
      path: '/my-scores'
      fullPath: '/my-scores'
      preLoaderRoute: typeof AppMyScoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-projects': {
      id: '/_app/my-projects'
      path: '/my-projects'
      fullPath: '/my-projects'
      preLoaderRoute: typeof AppMyProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-progress': {
      id: '/_app/my-progress'
      path: '/my-progress'
      fullPath: '/my-progress'
      preLoaderRoute: typeof AppMyProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-playground': {
      id: '/_app/my-playground'
      path: '/my-playground'
      fullPath: '/my-playground'
      preLoaderRoute: typeof AppMyPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-learning': {
      id: '/_app/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AppMyLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learning': {
      id: '/_app/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AppLearningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contributors': {
      id: '/_app/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof AppContributorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/sources': {
      id: '/_app/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AppAdminSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/grants': {
      id: '/_app/admin/grants'
      path: '/admin/grants'
      fullPath: '/admin/grants'
      preLoaderRoute: typeof AppAdminGrantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/announcements': {
      id: '/_app/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AppAdminAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppContributorsRoute: typeof AppContributorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLearningRoute: typeof AppLearningRoute
  AppMyLearningRoute: typeof AppMyLearningRoute
  AppMyPlaygroundRoute: typeof AppMyPlaygroundRoute
  AppMyProgressRoute: typeof AppMyProgressRoute
  AppMyProjectsRoute: typeof AppMyProjectsRoute
  AppMyScoresRoute: typeof AppMyScoresRoute
  AppNewcomersRoute: typeof AppNewcomersRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppQualityRoute: typeof AppQualityRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWorklogRoute: typeof AppWorklogRoute
  AppAdminAnnouncementsRoute: typeof AppAdminAnnouncementsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminGrantsRoute: typeof AppAdminGrantsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSourcesRoute: typeof AppAdminSourcesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContributorsRoute: AppContributorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLearningRoute: AppLearningRoute,
  AppMyLearningRoute: AppMyLearningRoute,
  AppMyPlaygroundRoute: AppMyPlaygroundRoute,
  AppMyProgressRoute: AppMyProgressRoute,
  AppMyProjectsRoute: AppMyProjectsRoute,
  AppMyScoresRoute: AppMyScoresRoute,
  AppNewcomersRoute: AppNewcomersRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppQualityRoute: AppQualityRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppTeamRoute: AppTeamRoute,
  AppWorklogRoute: AppWorklogRoute,
  AppAdminAnnouncementsRoute: AppAdminAnnouncementsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminGrantsRoute: AppAdminGrantsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSourcesRoute: AppAdminSourcesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PendingRoute: PendingRoute,
  SuspendedRoute: SuspendedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
